
############ working code starts ############
import sys
import pandas as pd
import ydata_profiling as profileReport
import datetime

sheetName = sys.argv[1]
tableName = sys.argv[2]

x = datetime.datetime.now()
filePath = './profilingReport/' + tableName + str(x.timestamp()) + '.html'
# filePath1 = './profilingReport/' + tableName + str(x.timestamp()) + '.json'

df = pd.read_csv(sheetName)
df.reset_index()

# removing null values to avoid errors
# df.fillna('', inplace=True)

# profile = profileReport.ProfileReport(df.describe(), title='DMAC Profiling Report', minimal =True)
profile = profileReport.ProfileReport(df, title = "DMAC Profiling Report", dataset = {

        "description": "This profiling report was generated by Mckinsol Technologies",

        "copyright_holder": "Mckinsol Technologies",

        "copyright_year": "2023",

        "url": "https://mckinsol.com/about-mckinsol-consulting-india/"

    }, correlations = None, interactions = None, missing_diagrams = None, dark_mode = True)
profile.to_file(output_file=filePath)
# profile.to_file(output_file=filePath1)
print(filePath)

# ######### working code ends ###########

# import sys,json
# # from turtle import title
# import pandas as pd
# import pandas_profiling as profileReport
# import datetime
# from pydantic_settings import BaseSettings

# sheetName=sys.argv[1]
# tableName=sys.argv[2]
# # fileFormat=sys.argv[3]

# x = datetime.datetime.now()
# filePath='./profilingReport/'+tableName+str(x.timestamp())+'.html'
# filePath1='./profilingReport/'+tableName+str(x.timestamp())+'.json'

# df = pd.read_csv(sheetName)
# df.reset_index() 

# profile = profileReport.ProfileReport(df,title='DMAC Profiling Report')
# profile.to_file(output_file=filePath)
# profile.to_file(output_file=filePath1)

# # removing null values to avoid errors  
# # df.fillna('',inplace = True)

# # print(df1.to_json(orient='records'))
# print(filePath)