import sys
import pandas as pd
import ydata_profiling as profileReport
import datetime
import dask.dataframe as dd
sheetName = sys.argv[1]
tableName = sys.argv[2]

x = datetime.datetime.now()
filePath = './profilingReport/' + tableName + str(x.timestamp()) + '.html'
filePath1 = './profilingReport/' + tableName + str(x.timestamp()) + '.json'
df1 = pd.read_csv(sheetName )

df = dd.read_csv(sheetName, dtype= df1.dtypes)
df.compute()
# df.reset_index()

# removing null values to avoid errors
# df.fillna('', inplace=True)

# profile = profileReport.ProfileReport(df.describe(), title='DMAC Profiling Report', minimal =True)
profile = profileReport.ProfileReport(df, title = "DMAC Profiling Report", dataset = {

        "description": "This profiling report was generated by Mckinsol Technologies",

        "copyright_holder": "Mckinsol Technologies",

        "copyright_year": "2023",

        "url": "https://mckinsol.com/about-mckinsol-consulting-india/"

    }, correlations = None, interactions = None, missing_diagrams = None, dark_mode = True)
profile.to_file(output_file=filePath)
profile.to_file(output_file=filePath1)
print(filePath)

